name: Test project
on: push # Run the workflow on push events
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - name: Install dependencies
              #npm ci downloads the exact versions of the dependencies that are in the package-lock.json file
              run: npm ci
            - name: Run tests
              run: npm test
    build:
        runs-on: ubuntu-latest
        #Adding a dependency of this build job on the test job, if the test job fails, the build job will not run
        needs: test
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
            - name: Install dependencies
              run: npm ci
            - name: Build the project
              run: npm run build
            - name: Upload the built project artifact
              uses: actions/upload-artifact@v3
              with:
                name: built-project
                path: dist
